# Generated by Django 3.2.8 on 2021-11-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('Pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numberofbeds', models.IntegerField()),
                ('hospitalimage', models.ImageField(upload_to='<django.db.models.fields.CharField>-<django.db.models.fields.related.ForeignKey>')),
                ('ratings', models.IntegerField()),
                ('fees', models.PositiveIntegerField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.location')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='doctorImages')),
                ('Qualfication', models.CharField(max_length=30)),
                ('Specilization', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('startingtime', models.TimeField(max_length=30)),
                ('endingtime', models.TimeField()),
                ('ratings', models.IntegerField()),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allapps.hospital')),
            ],
        ),
    ]
