# Generated by Django 3.2.8 on 2021-11-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='fees',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='numberofbeds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
