# Generated by Django 3.2.8 on 2021-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0002_auto_20211109_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Qualfication',
            new_name='Qualification',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
