# Generated by Django 3.2.8 on 2021-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0003_auto_20211109_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
