# Generated by Django 3.2.8 on 2021-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0004_auto_20211109_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='password',
        ),
        migrations.RemoveField(
            model_name='location',
            name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
