# Generated by Django 3.2.8 on 2021-11-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0005_auto_20211110_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(max_length=20)),
                ('is_login', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='allapps.hospital')),
            ],
        ),
    ]
