# Generated by Django 3.2.8 on 2021-11-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0006_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='is_login',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allapps.hospital'),
        ),
    ]
