# Generated by Django 3.2.8 on 2021-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0007_auto_20211110_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='picture',
            field=models.ImageField(null=True, upload_to='HosptialImages'),
        ),
    ]
