# Generated by Django 3.2.8 on 2021-11-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0010_hospital_discriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='discriptions',
            field=models.TextField(blank=True),
        ),
    ]
