# Generated by Django 3.2.8 on 2021-11-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0012_auto_20211112_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resetid', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=25)),
            ],
        ),
    ]
