# Generated by Django 3.2.8 on 2021-11-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0013_resetids'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='emailid',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resetids',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='allapps.hospital'),
            preserve_default=False,
        ),
    ]
