# Generated by Django 3.2.8 on 2021-11-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0014_auto_20211117_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allapps.hospital'),
        ),
    ]
