# Generated by Django 3.2.8 on 2021-11-18 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0015_alter_resetids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='otp',
            field=models.PositiveIntegerField(default=True, validators=[django.core.validators.MinValueValidator(111111), django.core.validators.MaxLengthValidator(999999)]),
            preserve_default=False,
        ),
    ]
