# Generated by Django 3.2.8 on 2021-11-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0016_sessions_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='otp',
        ),
    ]
