# Generated by Django 3.2.8 on 2021-11-18 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0017_remove_sessions_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='otp',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(111111), django.core.validators.MaxLengthValidator(999999)]),
        ),
    ]
